config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'

  # root 'posts#index'
  resources :posts do
    resources :opinions
  end   

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # Paginas estaticas
  get '/blog' => 'static_pages#blog', as: 'blog'
  get '/nosotros' => 'static_pages#about', as: 'about'
  get '/contacto' => 'static_pages#contact', as: 'contact'
  get '/nuestros_servicios' => 'static_pages#our_services', as: 'our_services'
  
  # Aquí deberían ir tadas las peticiones y actividades que realiza un cliente
  get '/cliente' => 'cliente/my_servises#index'
  namespace :cliente do
    resources :requests
    resources :my_servises
    resources :profile
  
    #TODO: Veri si sepueden usar scopes
    get 'requests/servicios/:consulta', to: 'requests#servicios'
    get 'tecnicos_interesados/destroy'
    get 'tecnicos_interesados/show'
    get 'tecnicos_interesados/perfil_tecnico/:worker_id', to: 'tecnicos_interesados#perfil_tecnico', as: 'tecnicos_interesados_perfil_tecnico'
    get 'tecnicos_interesados/index'
    get "my_servises/qualify/:id", to: "my_servises#qualify", as: "my_servises_qualify"
    post "my_servises/completar"
    get 'tecnicos_interesados/citar/:worker_id/:request_id/:year/:week', to: 'tecnicos_interesados#citar', as: 'tecnicos_interesados_citar'
    post 'tecnicos_interesados/apartar_cita/:worker_id/:request_id/:year/:week/:day/:hour', to: 'tecnicos_interesados#apartar_cita', as: 'tecnicos_interesados_apartar_cita'

  end

  # Aquí deberían ir tadas las peticiones y actividades que realiza un técnico
  get '/tecnico' => 'tecnico/my_services#index'
  namespace :tecnico do
    resources :free_services, :profile
    resources :my_services, except: [:show, :edit, :update]
    resources :supports, except: :index

    post "my_services/create_service" # Crear un nuevo servicio en la tabla servicios

    get 'accept/success'
    post 'accept/agree'  # Postularme para un servicio
    delete 'agenda/cancelar' # Cancelar mi postulacion para un servicio
    get 'agenda/trabajos'

  end

  # Aquí todas la peticiones de inicio de sesión
  devise_for :workers , controllers:{registrations: 'workers/registrations', sessions: 'workers/sessions'} 
  devise_for :customers, controllers:{registrations: 'customers/registrations', sessions: 'customers/sessions', omniauth_callbacks: "customers/omniauth_callbacks" }  

  devise_for :administrators , controllers:{registrations: 'administrators/registrations', sessions: 'administrators/sessions'} 
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end

  def blog
  end

  def home
  end

  def register
  end

  def owr_services
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
	
	# Obtener la direccion correcta del link servicios en el header dependiendo de el usuario
	def get_services_page 
		if customer_signed_in?
			cliente_requests_path
		elsif worker_signed_in?
			tecnico_free_services_path
		else
			our_services_path
		end
	end

end

app/views/static_pages/about.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-lg-12 text-center">
			<%= image_tag("nosotros.jpg", class: "img-responsive") %>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-lg-12">

			
			
			<div class="col-lg-6">		
						<div class="text-center texto-azul">	
			<h2><span>			Acerca de nosotros:	</span>	</h2></div>
		
			<div class="text">
			Somos un grupo de estudiantes de pregrado de ingeniería de sistemas, que quieren conectar personas a través de una aplicación web que pretende ser una plataforma que te de la capacidad de encontrar al técnico que necesitas, y para lo que necesites.
			</div>
			<div class="text">
			Si tienes un problema con un electrodoméstico, o cualquier aparato electrónico o digital, usa nuestro servicio para conectarte con la persona adecuada!
			</div>
			<h3>¿Quienes somos?</h3>

				<ul>
					<li>Juan Carlos Gama Roa
				</li>
					<li>Juan David Quintero</li>
					<li>Diego Abel Cruz</li>
					<li>Alejandro Sierra</li>
					<li>David Felipe Rodriguez</li>
				</ul>

			</div>
			<div class="col-lg-6">
			
				<%= image_tag("jovenes.jpg", class: "img-responsive") %>
			</div>
				
		</div>
	</div>
</div>

app/views/static_pages/blog.html.erb
<!-- Wrap -->
<div id="wrap"> 
  <!-- Progress  Bar -->
  <section class="sub-baner">
    <div class="container">
      <h3>Blog</h3>
      <ol class="breadcrumb">
        <li><a href="#">Inicio</a></li>
        <li class="active">Blog</li>
      </ol>
    </div>
  </section>
  
  <!-- Content -->
  <div id="content"> 
    
    <!-- Blog -->
    <section class="padding-top-100 padding-bottom-100">
      <div class="container">
        <div class="row">
          <div class="col-md-8"> 
            
            <!-- Blog -->
            <div class="blog-list"> 
              
              <!-- Article -->
              <article class="blog-post"> <img class="img-responsive" src="images/blog-img-1.jpg" alt="" >
                <div class="post-info"> 
                  <!-- Date -->
                  <div class="date"> 28 <span>Jul</span> </div>
                  <a href="#." class="post-tittle">¿Como saber si mi lavadora esta fallando?</a> 
                  <!-- Small Info -->
                  <div class="aut"> <i class="fa fa-user"></i><span>Admin</span> <i class="fa fa-folder-o"></i><span>servicios, tips, clientes</span> <i class="fa fa-comment-o"></i><span>2 Comentarios</span> </div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus.</p>
                </div>
              </article>
              
              <!-- Article -->
              <article class="blog-post"> <img class="img-responsive" src="images/blog-img-1.jpg" alt="" >
                <div class="post-info"> 
                  <!-- Date -->
                  <div class="date"> 28 <span>Jul</span> </div>
                  <a href="#." class="post-tittle">Consejos para durar más tiempo con mi televisor</a> 
                  <!-- Small Info -->
                  <div class="aut"> <i class="fa fa-user"></i><span>Admin</span> <i class="fa fa-folder-o"></i><span>servicios, tips, clientes</span> <i class="fa fa-comment-o"></i><span>2 Comentarios</span> </div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus.</p>
                </div>
              </article>
              
              <!-- Article -->
              <article class="blog-post"> <img class="img-responsive" src="images/blog-img-1.jpg" alt="" >
                <div class="post-info"> 
                  <!-- Date -->
                  <div class="date"> 28 <span>Jul</span> </div>
                  <a href="#." class="post-tittle">Televisores que me permiten usar menos energía</a> 
                  <!-- Small Info -->
                  <div class="aut"> <i class="fa fa-user"></i><span>Admin</span> <i class="fa fa-folder-o"></i><span>servicios, tips, clientes</span> <i class="fa fa-comment-o"></i><span>2 Comentarios</span> </div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh augue, suscipit a, scelerisque sed, lacinia in, mi. Cras vel lorem. Etiam pellentesque aliquet tellus. Phasellus pharetra nulla ac diam. Quisque semper justo at risus. Donec venenatis, turpis vel hendrerit interdum, dui ligula ultricies purus.</p>
                </div>
              </article>
              
            </div>
          </div>
          
          <!-- Side Bar -->
          <div class="col-md-4"> 
            
            <!-- Blog -->
            <div class="sidebar"> 
              <!-- Search -->
              <div class="search">
                <input class="form-control" type="search" placeholder="Buscar">
                <button type="submit"><i class="fa fa-search"></i></button>
              </div>
              
              <!-- Categories -->
              <h6 class="margin-top-50">Categorías</h6>
              <ul class="cate archive">
                <li><a href="#."> Tecnicos <span>4</span></a></li>
                <li><a href="#."> Usuarios <span>28</span></a></li>
                <li><a href="#."> Tips <span>12</span></a></li>
                <li><a href="#."> Despues del servicio <span>4</span></a></li>
                <li><a href="#."> Anecdotas<span>9</span></a></li>
              </ul>
              
              <!-- Recent Posts -->
              <h6 class="margin-top-50">Posts más recientes</h6>
              <ul class="papu-post margin-top-30">
                <li class="media">
                  <div class="media-left"> <a href="#"> <img class="media-object" src="images/r-post-img.jpg" alt=""></a> </div>
                  <div class="media-body"> <a class="media-heading" href="#.">Aquí viene el título de post y puede ir en 2 líneas de texto si es lo suficientemente largo </a> <span>Jul 28, 2016</span> </div>
                </li>
                <li class="media">
                  <div class="media-left"> <a href="#"> <img class="media-object" src="images/r-post-img-1.jpg" alt=""></a> </div>
                  <div class="media-body"> <a class="media-heading" href="#.">Título del post viene aquí</a> <span>Jul 18, 2015</span> </div>
                </li>
                <li class="media">
                  <div class="media-left"> <a href="#"> <img class="media-object" src="images/r-post-img-2.jpg" alt=""></a> </div>
                  <div class="media-body"> <a class="media-heading" href="#.">Aquí viene el título de post y puede ir en 2 líneas de texto si es lo suficientemente largo</a> <span>Jul 18, 2015</span> </div>
                </li>
              </ul>
              
              <!-- Recent Posts -->
              <h6 class="margin-top-50">Archivo</h6>
              <ul class="cate archive">
                <li><a href="#."> Septiembre 2017 <span>4</span></a></li>
                <li><a href="#."> Agosto 2017 <span>28</span></a></li>
                <li><a href="#."> Agosto 2016 <span>12</span></a></li>
                <li><a href="#."> Julio 2016 <span>4</span></a></li>
                <li><a href="#."> Junio 2016 <span>9</span></a></li>
              </ul>
              
              <!-- Tags -->
              <h6 class="margin-top-50">Etiquetas</h6>
              <ul class="tags">
                <li><a href="#.">Servicios </a></li>
                <li><a href="#.">Clientes </a></li>
                <li><a href="#.">Pagos </a></li>
                <li><a href="#.">Solicitar </a></li>
                <li><a href="#.">Credito </a></li>
                <li><a href="#.">Excelente </a></li>
                <li><a href="#.">Seguro</a></li>
                <li><a href="#.">tarjeta de credito </a></li>
                <li><a href="#.">habilidades </a></li>
                <li><a href="#.">mapa </a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/static_pages/contact.html.erb
<!-- Wrap -->
<div id="wrap"> 
  
  <!-- Progress  Bar -->
  <section class="sub-baner">
    <div class="container">
      <h3>Contáctenos</h3>
      <ol class="breadcrumb">
        <li><a href="#">Inicio</a></li>
        <li class="active">Contácto</li>
      </ol>
    </div>
  </section>
  
  <!-- Content -->
  <div id="content"> 
    
    <!-- Contact Us -->
    <section class="contact-us padding-top-100 padding-bottom-100">
      <div class="container">
        <div class="row"> 
          
          <!-- Contact Form -->
          <div class="col-md-7">
			<h3>Para contactarnos ingresa <br> los siguientes datos</h3>
			<form class="" method="post" action="#">
				
				<div class="form-group">
					<label for="name" class="cols-sm-2 control-label">Nombre</label>
					<div class="cols-sm-10">
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
							<input type="text" class="form-control" name="name" id="name"  placeholder="Ingrese su nombre"/>
						</div>
					</div>
				</div>
				
				<div class="form-group">
					<label for="lastname" class="cols-sm-2 control-label">Apellido</label>
					<div class="cols-sm-10">
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
							<input type="text" class="form-control" name="lastname" id="lastname"  placeholder="Ingrese su apellido"/>
						</div>
					</div>
				</div>
				

				<div class="form-group">
					<label for="email" class="cols-sm-2 control-label">Correo</label>
					<div class="cols-sm-10">
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-envelope fa" aria-hidden="true"></i></span>
							<input type="text" class="form-control" name="email" id="email"  placeholder="Ingrese su correo"/>
						</div>
					</div>
				</div>
				
				<div class="form-group">
					<label for="comment" class="cols-sm-2 control-label">Comentarios</label>
					<div class="cols-sm-10">
						<div class="input-group">
							<span class="input-group-addon"><i class="fa fa-comment" aria-hidden="true"></i></span>
							<input type="text" class="form-control" name="comment" id="comment"  placeholder="Ingrese sus comentarios"/>
						</div>
					</div>
				</div>


				<div class="form-group ">
					<a href="#" target="_blank" type="button" id="button" class="btn btn-primary btn-lg btn-block login-button">Enviar</a>
				</div>
				
			</form>
          </div>
          
          <!-- Contact Info -->
          <div class="col-md-5">
            <div class="contat-info">
              <h3>Llama <br>
                a cualquier hora! <span class="timing">ma-ju: 2pm-4pm Sa: 10am-5pm</span> </h3>
              
              <!-- Phone Info -->
              <ul>
                <li><i class="fa fa-phone"></i>
                  <h6>Atención al cliente</h6>
                  <h3><span>100 200</span> 301</h3>
                </li>
                <li><i class="fa fa-mobile-phone"></i>
                  <h6>soporte técnico</h6>
                  <h3><span>100 200</span> 301</h3>
                </li>
                <li><i class="fa fa-database"></i>
                  <h6>Problemas con tus pagos</h6>
                  <h3><span>100 200</span> 301</h3>
                </li>
              </ul>
              <h3  class="margin-top-50">Nuestra <br>
                Ubicación </h3>
              <ul>
                <li><i class="fa fa-home"></i>
                  <h6>Edificio 401 Julio Garavito<br>
                    Universidad Nacional de Colombia</h6>
                  <a href="#.">soporte@lakaiteam.com</a><br>
                  <a href="#.">unal.edu.co</a> </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>
    
    <!-- ESPACIO PARA  MAPA -->
    <section class="map-block">
      <div class="map-wrapper" id="map-canvas" data-lat="-37.814199" data-lng="144.961560" data-zoom="13" data-style="1"></div>
      <div class="markers-wrapper addresses-block"> <a class="marker" data-rel="map-canvas" data-lat="-37.814199" data-lng="144.961560" data-string="Envato"></a> </div>
    </section>
  </div>

</div>

app/views/static_pages/home.html.erb
  <!-- Banner -->
<section class="bnr-slide">      
    <!-- Slide 1 -->
    <div class="bg-slide-1">
      <div class="position-center-center">
        <div class="container">
          <h6>¡Cuando lo necesitas,</h6>
          <h4>Donde lo necesitas!<span>FACIL</span></h4>
          <%= link_to new_customer_registration_path, class: "btn" do %>
            Contratar servicio <i class="fa fa-long-arrow-right"></i>
          <% end -%>
          <%= link_to  new_worker_registration_path, class: "btn btn-fill" do%>
            Soy Técnico<i class="fa fa-long-arrow-right"></i>
          <% end %>
        </div>

      </div>
    </div>
</section>


  <!-- Content -->
  <div id="content"> 
    
    <!-- Services -->
    <section class="power-hosting padding-top-100 padding-bottom-100">
      <div class="container"> 
        
        <!-- Tittle -->
        <div class="heading">
          <h2>UNA PLATAFORMA PARA FACILITAR TU VIDA</h2>
        </div>
        <ul class="row">
          
          <!-- 24/7 support -->
          <li class="col-md-3">
            <div class="icon"> <i class="fa fa-volume-control-phone"></i> </div>
            <h5>Soporte 24/7</h5>
            <p>Encuentra un técnico cerca a ti, a cualquier hora del dia y cualquier día de la semana.</p>
            <a href="/nosotros" class="btn">Más Información<i class="fa fa-long-arrow-right"></i></a> </li>
          
          <!-- Pro-Team -->
          <li class="col-md-3">
            <div class="icon"> <i class="fa fa-users"></i> </div>
            <h5>Técnicos calificados</h5>
            <p>Contamos con personal 100% calificado para solucionar cualquier problema que tengas.</p>
            <a href="/nosotros" class="btn">Más Información<i class="fa fa-long-arrow-right"></i></a> </li>
          
          <!-- Happy Customers -->
          <li class="col-md-3">
            <div class="icon"> <i class="fa fa-heart-o"></i> </div>
            <h5>clientes satisfechos</h5>
            <p>Nuestros clientes nos recomiendan, puedes ver sus comentarios sobre nuestros servicios.</p>
            <a href="/nosotros" class="btn">Más Información<i class="fa fa-long-arrow-right"></i></a> </li>
          
          <!-- Best Prices -->
          <li class="col-md-3">
            <div class="icon"> <i class="fa fa-money"></i> </div>
            <h5>los mejores precios</h5>
            <p>Contamos con los mejores precios del mercado.</p>
            <a href="/nosotros" class="btn">Más Información<i class="fa fa-long-arrow-right"></i></a> </li>
        </ul>
      </div>
    </section>
    
    <!-- SMALL INTRO -->
    <section class="bg-parrall padding-top-100 padding-bottom-100">
      <div class="container">
        <div class="text-center">
          <h2>Una aplicacion pensada <span>para ti</span></h2>
          <a href="/registro" class="btn">Contratar <i class="fa fa-long-arrow-down"></i></a> </div>
      </div>
    </section>
    
    <!-- Choose Services -->
    <section class="padding-top-100 padding-bottom-100">
      <div class="container"> 
        
        <!-- Tittle -->
        <div class="heading">
          <h2>SERVICIOS DESTACADOS EN BOGOTA</h2>
        </div>
        
        <!-- Choose Plan -->
        <div class="choose-plan">
          <ul class="row">
            
            <!-- columna1 -->
            <li class="col-md-3">
              <article>
                <h4>Reparaciòn de Computadores</h4>

                <ul>
                  <li>Más de 200 Técnicos </li>
                  <li>Este mes descuento del 20%</li>
                  <li></li>
                  <li></li>
                </ul>
                <!-- Choose --> 
                <a href="#." class="btn">Contratar servicio</a> </article>
            </li>
            
            <!-- column2 -->
            <li class="col-md-3">
              <article>
                <h4>Reparaciòn de Lavadoras</h4>

                <ul>
                  <li>Más de 60 Técnicos</li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                </ul>
                <!-- Choose --> 
                <a href="#." class="btn">Contratar servicio</a> </article>
            </li>
            
            <!-- columna3 -->
            <li class="col-md-3">
              <article>
                <h4>Reparaciòn de Televisores</h4>

                <ul>
                  <li>Más de 100 Técnicos </li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                </ul>
                <!-- Choose --> 
                <a href="#." class="btn">Contratar servicio</a> </article>
            </li>
            
            <!-- Platinum -->
            <li class="col-md-3">
              <article>
                <h4>Reparaciòn de celulares</h4>

                <ul>
                  <li>Más de 80 Técnicos </li>
                  <li>Este mes descuento del 30%</li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                </ul>
                <!-- Choose --> 
                <a href="#." class="btn">Contratar servicio</a> </article>
            </li>
          </ul>
        </div>
      </div>
    </section>
    
    <!-- Choose Services -->
    
    <!-- Choose Services -->
    <section class="padding-top-100 padding-bottom-100">
      <div class="container"> 
        
        <!-- Tittle -->
        <div class="heading">
          <h2>TÉCNICOS DESTACADOS EN BOGOTA</h2>
        </div>
        
        <!-- Choose Plan -->
        <div class="choose-plan">
          <ul class="row">
            
            <!-- columna1 -->
            <li class="col-md-3">
              <article>
                <h4>DIEGO CRUZ</h4>

                <ul>
                  <li>Técnico de Televisores</li>
                  <li>Un 96% de clientes lo recomiendan</li>
                  <li></li>
                  <li></li>
                </ul>
                <!-- Choose --> 
                <a href="#." class="btn">Contratar servicio</a> </article>
            </li>
            
            <!-- column2 -->
            <li class="col-md-3">
              <article>
                <h4>JUAN GAMA</h4>

                <ul>
                  <li>Técnico de Computadores</li>
                  <li>Empleado de año</li>
                  <li>Disponible las 24 horas</li>
                  <li>Un 98% lo recomienda</li>
                  <li></li>
              
                </ul>
                <!-- Choose --> 
                <a href="#." class="btn">Contratar servicio</a> </article>
            </li>
            
            <!-- columna3 -->
            <li class="col-md-3">
              <article>
                <h4>GUSTAVO PUENTES</h4>

                <ul>
                  <li>Tecnico de Impresoras </li>
                  <li>Un 78% lo recomienda</li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                  <li></li>
                </ul>
                <!-- Choose --> 
                <a href="#." class="btn">Contratar servicio</a> </article>
            </li>
            
            <!-- Platinum -->
            <li class="col-md-3">
              <article>
                <h4>ALEJANDRO SIERRA</h4>

                <ul>
                  <li>Técnico de Celulares</li>
                  <li>Empleado del mes</li>
                  <li>Un 97% lo recomienda</li>
                  <li></li>                </ul>
                <!-- Choose --> 
                <a href="#." class="btn">Contratar servicio</a> </article>
            </li>
          </ul>
        </div>
      </div>
    </section>
    
    <!-- Choose Services -->
    
    
    <section class="testimonial padding-top-150 padding-bottom-150">
      <div class="container"> 
        
        <!-- Tittle -->
        <div class="heading">
          <h2>lo que otros usuarios han opinado <small>testimoniales</small></h2>
        </div>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> 
          
          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox"> 
            
            <!-- Slides 1 -->
            <div class="item active">
              <p>Pude reparar mi computador! El tècnico era una persona muy atenta y servicial.</p>
            </div>
            
            <!-- Slides 2 -->
            <div class="item">
              <p>Pude reparar mi computador! El tècnico era una persona muy atenta y servicial.</p>
            </div>
            
            <!-- Slides 3 -->
            <div class="item">
              <p>Pude reparar mi computador! El tècnico era una persona muy atenta y servicial.</p>
            </div>
          </div>
          
          <!-- Indicators -->
          <ol class="carousel-indicators">
            
            <!-- THUMB 1 -->
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active">
              <div class="media-left"> <%= image_tag("testi-avatar.jpg") %> </div>
              <div class="media-body">
                <h6>Felipe Rodriguez</h6>
                <span>ferodriguez</span> </div>
            </li>
            
            <!-- THUMB 2 -->
            
            <li data-target="#carousel-example-generic" data-slide-to="1">
              <div class="media-left"> <%= image_tag("testi-avatar.jpg") %>  </div>
              <div class="media-body ">
                <h6>Tatiana Calderon</h6>
                <span>taticalderono</span> </div>
            </li>
            
            <!-- THUMB 3 -->
            
            <li data-target="#carousel-example-generic" data-slide-to="2">
              <div class="media-left"> <%= image_tag("testi-avatar.jpg") %> </div>
              <div class="media-body ">
                <h6>Henry Ovalle</h6>
                <span>henryovalle22</span> </div>
            </li>
          </ol>
        </div>
      </div>
    </section>
  </div>

app/views/static_pages/our_services.html.erb
<h1>Nuestros Servicios</h1>
<h4>Página Informativa</h4>