config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'

  # root 'posts#index'
  resources :posts do
    resources :opinions
  end   

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # Paginas estaticas
  get '/blog' => 'static_pages#blog', as: 'blog'
  get '/nosotros' => 'static_pages#about', as: 'about'
  get '/contacto' => 'static_pages#contact', as: 'contact'
  get '/nuestros_servicios' => 'static_pages#our_services', as: 'our_services'
  
  # Aquí deberían ir tadas las peticiones y actividades que realiza un cliente
  get '/cliente' => 'cliente/my_servises#index'
  namespace :cliente do
    resources :requests
    resources :my_servises
    resources :profile
  
    #TODO: Veri si sepueden usar scopes
    get 'requests/servicios/:consulta', to: 'requests#servicios'
    get 'tecnicos_interesados/destroy'
    get 'tecnicos_interesados/show'
    get 'tecnicos_interesados/perfil_tecnico/:worker_id', to: 'tecnicos_interesados#perfil_tecnico', as: 'tecnicos_interesados_perfil_tecnico'
    get 'tecnicos_interesados/index'
    get "my_servises/qualify/:id", to: "my_servises#qualify", as: "my_servises_qualify"
    post "my_servises/completar"
    get 'tecnicos_interesados/citar/:worker_id/:request_id/:year/:week', to: 'tecnicos_interesados#citar', as: 'tecnicos_interesados_citar'
    post 'tecnicos_interesados/apartar_cita/:worker_id/:request_id/:year/:week/:day/:hour', to: 'tecnicos_interesados#apartar_cita', as: 'tecnicos_interesados_apartar_cita'

  end

  # Aquí deberían ir tadas las peticiones y actividades que realiza un técnico
  get '/tecnico' => 'tecnico/my_services#index'
  namespace :tecnico do
    resources :free_services, :profile
    resources :my_services, except: [:show, :edit, :update]
    resources :supports, except: :index

    post "my_services/create_service" # Crear un nuevo servicio en la tabla servicios

    get 'accept/success'
    post 'accept/agree'  # Postularme para un servicio
    delete 'agenda/cancelar' # Cancelar mi postulacion para un servicio
    get 'agenda/trabajos'

  end

  # Aquí todas la peticiones de inicio de sesión
  devise_for :workers , controllers:{registrations: 'workers/registrations', sessions: 'workers/sessions'} 
  devise_for :customers, controllers:{registrations: 'customers/registrations', sessions: 'customers/sessions', omniauth_callbacks: "customers/omniauth_callbacks" }  

  devise_for :administrators , controllers:{registrations: 'administrators/registrations', sessions: 'administrators/sessions'} 
end

app/controllers/tecnico/accept_controller.rb
class Tecnico::AcceptController < ApplicationController
  
  before_action :authenticate_worker!
  
  def success
  end

  # Aceptar una peticion de usuario
  def agree
    
    worker = current_worker.id
    req = params[:request]
    if not (Proposal.exists?(worker_id: worker, request_id: req))
      #@shd = Schedule.create(:worker_id => worker, :customer_id => client_id, :request_id => req, :date => fecha)
      @shd = Proposal.create(worker_id: worker, request_id: req)
    end

    redirect_to tecnico_agenda_trabajos_path

  end
end

app/controllers/tecnico/agenda_controller.rb
class Tecnico::AgendaController < ApplicationController
  before_action :authenticate_worker!
  
  def trabajos
    @Pendientes = current_worker.peticiones_pendientes(params[:pendientes_page])
    @Agendadas = current_worker.schedules
  end

  def cancelar
    Proposal.destroy( params[:destr] )
    redirect_to tecnico_agenda_trabajos_path
  end

  

end

app/controllers/tecnico/free_services_controller.rb
class Tecnico::FreeServicesController < ApplicationController
  before_action :authenticate_worker!

  def index
    @requests = current_worker.myFreeServices_paginate( params[:page] )
  end

  def show

    @peticion = Request.find(params[:id])

    #@bounding_box = [{lat:  @cort1, lng: @cort1}, { lat: @cortc, lng: @corc1}]
    #@lat = @cor1
    #@lng = @cor2

  end
  
  def new
  end

  def edit
  end
  
end

#https://www.youtube.com/watch?v=W0juXNFLd6w

app/controllers/tecnico/my_services_controller.rb
class Tecnico::MyServicesController < ApplicationController
  before_action :authenticate_worker!

  def index
    skills = current_worker.services
    @services = skills.paginate(page: params[:page], per_page: 10)

    @soportes = current_worker.supports.paginate(page: params[:page], per_page: 10)
  end

  # GET: Para Agregar una nueva habilidad al técnico
  def new
  end

  # DELETE: Para eliminar una habilidad del técnico
  def destroy
    request_skill.destroy
    flash[:success] = "Habilidad eliminada correctamente"
    redirect_to tecnico_my_services_path
  end

  # POST: Crea una nueva habilidad para el técnico
  def create
    # Verificar que el tecnico no preste el servicio
    if current_worker.service_ids.include?(service_id)
      flash.now[:warning] = "Esa habilidad ya la tienes"
      redirect_to tecnico_my_services_path
      return 
    end

    # Guardar la nueva habilidad en la base de datos
    tran = Skill.create(worker_id: current_worker.id, service_id: service_id)

    if tran.valid?
      flash[:success] = "Tu habilidad se ha Agregado correctamente"
      redirect_to tecnico_my_services_path
    else
      render :new
    end
  end

  # POST: Crea un nuevo servicio 
  def create_service
    # Guardar el servicio en la base de datos
    tran = Service.create(description: service_description)

    if tran.valid?
      flash[:success] = "Servicio creado"
    else
      flash[:danger] = "Ha ocurrido un error !!"
    end
      redirect_to new_tecnico_my_service_path
  end
  
  private 

  def request_service
      current_worker.services.find(params[:id])
  end

  def request_skill
      current_worker.skills.find_by(service_id: params[:id])
  end

  def service_id
    params.require(:new_skill).permit(:service_id)[:service_id].to_i
  end

  def service_description
    params.require(:new_service).permit(:description)[:description]
  end

end

app/controllers/tecnico/profile_controller.rb
class Tecnico::ProfileController < ApplicationController
  before_action :authenticate_worker!
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/controllers/tecnico/supports_controller.rb
class Tecnico::SupportsController < ApplicationController
	before_action :authenticate_worker!

	def new
		@support = Support.new
	end

	def create
		support = Support.new

		support.worker_id = current_worker.id
		support.document = request_support

		if support.valid?
			support.save
			flash[:success] = "Tu archivo se ha cargado correctamente"
			redirect_to tecnico_my_services_path
		else
			redirect_to new_tecnico_support_path
		end

	end

	def destroy
		request_support = current_worker.supports.find_by(id: params[:id])
    if !request_support.nil?
    	request_support.destroy
    	flash[:success] = "Habilidad eliminada correctamente"
    end

    redirect_to tecnico_my_services_path
    
  end

	private 

	def request_support
		params.require(:support).permit(:document)[:document]
	end

end

app/helpers/tecnico/accept_helper.rb
module Tecnico::AcceptHelper
end

app/helpers/tecnico/agenda_helper.rb
module Tecnico::AgendaHelper
end

app/helpers/tecnico/supports_helper.rb
module Tecnico::SupportsHelper
end

app/views/tecnico/free_services/edit.html.erb
<%= render 'tecnico/menu' %>
<h1>FreeServices#edit</h1>
<p>Find me in app/views/cliente/free_services/edit.html.erb</p>

app/views/tecnico/free_services/index.html.erb
<!-- Content -->
<div id="content" class="container-fluid fondo-caja-login"> 
  <div class="row">
    <%= render 'tecnico/menu' %>
    <div class="col-lg-9">

      <div class="text-center texto-azul"><h2>Solicitudes</h2></div>
      
      <div class="table-responsive">
        
        <%= will_paginate @requests %>

        <table class="table table-bordered">
          <%# HEADER DE LA TABLA DE PETICIONES %>
          <thead>
            <tr>
              <th>Nombre del cliente</th>
              <th>Categoría del servicio</th>
              <th>Articulo</th>
              <th>Descripcion del articulo</th>
            </tr>
          </thead>
          
          <%# CUERPO DE LA TABLA DE PETICIONES %>
          <tbody>
            
            <% @requests.reverse_each do |req| %>
              <tr>
                <!-- QUITAR LA PARTE DE WORKER ID DEL IF SI SE QUIERE QUE UN SERVICIO SOLO SEA ACEPTADO POR UN Y SOLO UN TECNICO -->
                <% if not Proposal.exists?(request_id: req) %>
                  <td><%= req.customer.name %></td>
                  <td><%= req.service.description %></td>
                  <td><%= req.article %></td>
                  <td><%= req.description %> </td>
                
                  <%# LINKS PARA EDITAR O ELIMINAR LOS REQUERIMIENTOS DE SERVICIOS PUEDEN SER OPCIONALES %>
                  <td>
                    <%= link_to tecnico_free_service_path(req), method: :get, class: 'btn btn-primary btn-sm ' do %>
                      <span class="fa fa-eye"></span> Detalles
                    <% end %>
                  </td>
<<<<<<< HEAD
=======
                  <%#end%>
>>>>>>> correcciones_finales
                <% end %>
              </tr>
            <% end %>

          </tbody>
        </table>
        <%= will_paginate @requests %>
      </div>
    </div>
  </div>
</div>

app/views/tecnico/free_services/new.html.erb
<div class="conteiner-fluid">
	<%= render 'tecnico/menu' %>

		<div>
			<p>El servicio ha sido aceptado satisfactoriamente.</p>
			<a href="/tecnico/free_services" class="btn btn-primary btn-lg active" role="button">Regresar a servicios</a>
        </div>
        
        


</div>

app/views/tecnico/free_services/show.html.erb
<div id="content" class="container-fluid fondo-caja-login"> 
  <div class="row">
    <%= render 'tecnico/menu' %>
    <div class="col-lg-9">

      <div class="text-center texto-azul"><h2>Detalles de la Solicitud</h2></div>
      
      <div class="table-responsive">
        

        <table class="table table-bordered">
          <%# HEADER DE LA TABLA DE PETICIONES %>
          <thead class="thead-dark">
            <tr>
              <th>Nombre del cliente</th>
              <th>Categoría del servicio</th>
              <th>Artículo</th>
              <th>Descripcion del articulo</th>
              <th>Direccion del servicio</th>
              <th>Fecha de creación</th>
            </tr>
          </thead>
          
          <%# CUERPO DE LA TABLA DE PETICIONES %>
          <tbody>
          <td><%=@peticion.customer.name %></td>
          <td><%=@peticion.service.description %></td>
          <td><%=@peticion.article %></td>
          <td><%=@peticion.description %></td>

          <td><%@peticion.customer.address %></td>
          <td><%@peticion.customer.phone_number %></td>
          <td><%@peticion.customer.email %></td>
          <td><%=@peticion.created_at %></td>
          </tbody>
      
        </table>
      </div>
      
      <div class="text-center">
        <%= link_to tecnico_accept_agree_path(:client => @peticion.customer.id, :request => @peticion.id), method: :post, class: 'btn btn-lg btn-success ' do %>
          <span class="fa fa-check"></span> Aceptar servicio
        <% end %>          
      </div>

      <td>
        <%= link_to "Aceptar Servicio", tecnico_accept_agree_path(:client => @peticion.customer.id, :request => @peticion.id), method: :post, class:"btn btn-info" %>
      </td>


      <%@corc1 = @peticion.customer.latitude %>
      <%@corc2 = @peticion.customer.longitude %>
      <%@cort1 = current_worker.latitude %>
      <%@cort2 = current_worker.longitude %>


      <!--<p>Direccion Cliente:</p>-->
      <%@peticion.customer.address %>
      <%@corc1%>
      <%@corc2%>
      <%@cort1%>
      <%@cort1%>

      <!--<p>Direccion Tecnico:</p>-->   
      <%=current_worker.address%>

      <div class="text-center texto-azul"><h2>Detalles de Ubicación</h2></div>

      <div style='width: 100%;'>
        <div id="map" style='width: 100%; height: 600px;'>
        <script>



          var handler = Gmaps.build('Google');
          handler.buildMap({ provider: {
            zoomControl: true,
            zoom: 2,}, internal: {id: 'map'}}, function(){
            var markers = handler.addMarkers([
            {
              "lat": <%= @cort1 %>,
              "lng": <%= @cort2 %>,

              "picture": {
                "url": "http://maps.google.com/mapfiles/ms/icons/red-dot.png",
                "width":  50,
                "height": 50,
  
              },
              "infowindow": "Tú"
            }
          ]);

        var markers2 = handler.addMarkers([
        {
          "lat": <%= @corc1 %>,
          "lng": <%= @corc2 %>,

          "picture": {
            "url": "http://maps.google.com/mapfiles/ms/icons/red-dot.png",
            "width":  50,
            "height": 50,

          },
          "infowindow": "Cliente: <%=@peticion.customer.name %>, <%=@peticion.customer.address %>"
        }


      ]);

      handler.bounds.extendWith(markers);
      handler.fitMapToBounds(6);
      handler.getMap().setZoom(12);
      
      });

        </script>


        </div>
      </div>
  
    </div>
    
  </div>
  
  <!-- Para quemar el mapa en la vista 
    KEY de la API es : AIzaSyDc5J3WwsVQUOgYTMvLcnQmL-0wvdgaHss
  -->
</div>