config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'

  # root 'posts#index'
  resources :posts do
    resources :opinions
  end   

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # Paginas estaticas
  get '/blog' => 'static_pages#blog', as: 'blog'
  get '/nosotros' => 'static_pages#about', as: 'about'
  get '/contacto' => 'static_pages#contact', as: 'contact'
  get '/nuestros_servicios' => 'static_pages#our_services', as: 'our_services'
  
  # Aquí deberían ir tadas las peticiones y actividades que realiza un cliente
  get '/cliente' => 'cliente/my_servises#index'
  namespace :cliente do
    resources :requests
    resources :my_servises
    resources :profile
  
    #TODO: Veri si sepueden usar scopes
    get 'requests/servicios/:consulta', to: 'requests#servicios'
    get 'tecnicos_interesados/destroy'
    get 'tecnicos_interesados/show'
    get 'tecnicos_interesados/perfil_tecnico/:worker_id', to: 'tecnicos_interesados#perfil_tecnico', as: 'tecnicos_interesados_perfil_tecnico'
    get 'tecnicos_interesados/index'
    get "my_servises/qualify/:id", to: "my_servises#qualify", as: "my_servises_qualify"
    post "my_servises/completar"
    get 'tecnicos_interesados/citar/:worker_id/:request_id/:year/:week', to: 'tecnicos_interesados#citar', as: 'tecnicos_interesados_citar'
    post 'tecnicos_interesados/apartar_cita/:worker_id/:request_id/:year/:week/:day/:hour', to: 'tecnicos_interesados#apartar_cita', as: 'tecnicos_interesados_apartar_cita'

  end

  # Aquí deberían ir tadas las peticiones y actividades que realiza un técnico
  get '/tecnico' => 'tecnico/my_services#index'
  namespace :tecnico do
    resources :free_services, :profile
    resources :my_services, except: [:show, :edit, :update]
    resources :supports, except: :index

    post "my_services/create_service" # Crear un nuevo servicio en la tabla servicios

    get 'accept/success'
    post 'accept/agree'  # Postularme para un servicio
    delete 'agenda/cancelar' # Cancelar mi postulacion para un servicio
    get 'agenda/trabajos'

  end

  # Aquí todas la peticiones de inicio de sesión
  devise_for :workers , controllers:{registrations: 'workers/registrations', sessions: 'workers/sessions'} 
  devise_for :customers, controllers:{registrations: 'customers/registrations', sessions: 'customers/sessions', omniauth_callbacks: "customers/omniauth_callbacks" }  

  devise_for :administrators , controllers:{registrations: 'administrators/registrations', sessions: 'administrators/sessions'} 
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :customer
	belongs_to :service
	has_many :proposal, dependent: :delete_all
	
	validates :article, presence: true
	validates :description, presence: true
	#validates :legacy_code, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
	#validates :description, presence: true
end

app/controllers/cliente/requests_controller.rb
class Cliente::RequestsController < ApplicationController
  before_action :authenticate_customer!
  
  def servicios
    consulta = params[:consulta]
    @resultado = Service.where( "description LIKE ?", "%#{consulta}%")
    respond_to do |format|
      format.json {render :json => @resultado.to_json}
    end
  end
  
  # GET /requests
  # GET /requests.json
  def index
    @requests = current_customer.request
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])
  end

  # GET /requests/new
  def new
    @request = Request.new
    @Servicios = Service.all
  end

  # GET /requests/1/edit
  def edit
    set_request
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.customer_id = current_customer.id
    respond_to do |format|
      if @request.save #Si fue existosa la creación
        puts "Guardo !!!!"
        format.html { redirect_to cliente_requests_url, notice: 'Request was successfully created.' }
      else
        format.html { render :new}
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
      respond_to do |format|
      if set_request.update(request_params)
        format.html { redirect_to cliente_requests_url, notice: 'Request was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    set_request.destroy
    respond_to do |format|
      format.html { redirect_to cliente_requests_url, notice: 'Request was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit( :article, :service_id, :description, :fecha_servicio)
    end
end

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :article %>
    <%= form.text_field :article, id: :request_article %>
  </div>

  <div class="field">
    <%= form.label :service_tipe %>
    <%= form.text_field :service_tipe, id: :request_service_tipe %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :request_description %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_area :address, id: :request_address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @request.article %>
</p>

<p>
  <strong>Service tipe:</strong>
  <%= @request.service_tipe %>
</p>

<p>
  <strong>Description:</strong>
  <%= @request.description %>
</p>

<p>
  <strong>Address:</strong>
  <%= @request.address %>
</p>

<%= link_to 'Edit', edit_request_path(@request) %> |
<%= link_to 'Back', requests_path %>