config/routes.rb
Rails.application.routes.draw do

  get 'admins/index'

  # root 'posts#index'
  resources :posts do
    resources :opinions
  end   

  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

  # Paginas estaticas
  get '/blog' => 'static_pages#blog', as: 'blog'
  get '/nosotros' => 'static_pages#about', as: 'about'
  get '/contacto' => 'static_pages#contact', as: 'contact'
  get '/nuestros_servicios' => 'static_pages#our_services', as: 'our_services'
  
  # Aquí deberían ir tadas las peticiones y actividades que realiza un cliente
  get '/cliente' => 'cliente/my_servises#index'
  namespace :cliente do
    resources :requests
    resources :my_servises
    resources :profile
  
    #TODO: Veri si sepueden usar scopes
    get 'requests/servicios/:consulta', to: 'requests#servicios'
    get 'tecnicos_interesados/destroy'
    get 'tecnicos_interesados/show'
    get 'tecnicos_interesados/perfil_tecnico/:worker_id', to: 'tecnicos_interesados#perfil_tecnico', as: 'tecnicos_interesados_perfil_tecnico'
    get 'tecnicos_interesados/index'
    get "my_servises/qualify/:id", to: "my_servises#qualify", as: "my_servises_qualify"
    post "my_servises/completar"
    get 'tecnicos_interesados/citar/:worker_id/:request_id/:year/:week', to: 'tecnicos_interesados#citar', as: 'tecnicos_interesados_citar'
    post 'tecnicos_interesados/apartar_cita/:worker_id/:request_id/:year/:week/:day/:hour', to: 'tecnicos_interesados#apartar_cita', as: 'tecnicos_interesados_apartar_cita'

  end

  # Aquí deberían ir tadas las peticiones y actividades que realiza un técnico
  get '/tecnico' => 'tecnico/my_services#index'
  namespace :tecnico do
    resources :free_services, :profile
    resources :my_services, except: [:show, :edit, :update]
    resources :supports, except: :index

    post "my_services/create_service" # Crear un nuevo servicio en la tabla servicios

    get 'accept/success'
    post 'accept/agree'  # Postularme para un servicio
    delete 'agenda/cancelar' # Cancelar mi postulacion para un servicio
    get 'agenda/trabajos'

  end

  # Aquí todas la peticiones de inicio de sesión
  devise_for :workers , controllers:{registrations: 'workers/registrations', sessions: 'workers/sessions'} 
  devise_for :customers, controllers:{registrations: 'customers/registrations', sessions: 'customers/sessions', omniauth_callbacks: "customers/omniauth_callbacks" }  

  devise_for :administrators , controllers:{registrations: 'administrators/registrations', sessions: 'administrators/sessions'} 
end

app/controllers/cliente/my_servises_controller.rb
class Cliente::MyServisesController < ApplicationController
  before_action :authenticate_customer!
  
  def index
  end

  def new
  end

  def show
  	@content_request = set_request
    @mess = @content_request.content
  end

  def edit
  end

  def qualify
    @cita = params[:id]
    worker = Schedule.find(@cita).worker.id
    @complete = CompleteWork.create(worker_id: worker)
  end
  
  def completar
    cita_id = params[:cita_id]
    @complete = CompleteWork.create(completar_params)
    Schedule.destroy(cita_id)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit( :article, :service_tipe, :description, :address)
    end
    
    def completar_params
      params.require(:complete_work).permit(:worker_id, :comentario, :calificacion)
    end
end

app/controllers/cliente/profile_controller.rb
class Cliente::ProfileController < ApplicationController
  before_action :authenticate_customer!
  
  def index
  end

  def new
  end

  def show
  end

  def edit
  end
end

app/controllers/cliente/requests_controller.rb
class Cliente::RequestsController < ApplicationController
  before_action :authenticate_customer!
  
  def servicios
    consulta = params[:consulta]
    @resultado = Service.where( "description LIKE ?", "%#{consulta}%")
    respond_to do |format|
      format.json {render :json => @resultado.to_json}
    end
  end
  
  # GET /requests
  # GET /requests.json
  def index
    @requests = current_customer.request
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])
  end

  # GET /requests/new
  def new
    @request = Request.new
    @Servicios = Service.all
  end

  # GET /requests/1/edit
  def edit
    set_request
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.customer_id = current_customer.id
    respond_to do |format|
      if @request.save #Si fue existosa la creación
        puts "Guardo !!!!"
        format.html { redirect_to cliente_requests_url, notice: 'Request was successfully created.' }
      else
        format.html { render :new}
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
      respond_to do |format|
      if set_request.update(request_params)
        format.html { redirect_to cliente_requests_url, notice: 'Request was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    set_request.destroy
    respond_to do |format|
      format.html { redirect_to cliente_requests_url, notice: 'Request was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit( :article, :service_id, :description, :fecha_servicio)
    end
end

app/controllers/cliente/tecnicos_interesados_controller.rb
class Cliente::TecnicosInteresadosController < ApplicationController
  before_action :authenticate_customer!

  def index
    @peticiones = current_customer.tecnicos_postulados
    @Agendadas = current_customer.schedule
  end

  def show
  end

  def destroy
  end

  # TODO: Verificar que el tecnico este en la lista de postulados 
  # para que no acceda a peticiones fantasma o no autorizadas

  def citar
    @request = Request.find(params[:request_id])
    @tecnico = Worker.find(params[:worker_id])
    @week = params[:week].to_i
    @year = params[:year].to_i
  	@horarios_ocupados = @tecnico.citas_agendadas(@year, @week )
  end

  def apartar_cita
    request = Request.find(datos_cita[:request_id])

    # Crear la cita en la agenda
    cita_nueva = Schedule.new
    
    fecha = Date.commercial(year = datos_cita[:year].to_i, cweek = datos_cita[:week].to_i)
    fecha += datos_cita[:day].to_i.days + datos_cita[:hour].to_i.hours
    
    cita_nueva.date = fecha

    cita_nueva.customer_id = current_customer.id
    cita_nueva.service_id = request.service_id
    cita_nueva.worker_id = datos_cita[:worker_id]

    cita_nueva.save

    #Eliminar el request
    request.destroy

    #TODO: Hacer notificaciones para los tecnicos

    #mensaje de correcto =D
    flash[:success] = "La cita ha sido agendada correctamente"

    #Redireccion
    redirect_to cliente_tecnicos_interesados_index_path
  end

  def perfil_tecnico
    @worker = Worker.find(params[:worker_id])
  end

  private 

  def datos_cita
    params.permit(:worker_id, :request_id, :year, :week, :day, :hour)
  end

end

app/controllers/tecnico/profile_controller.rb
class Tecnico::ProfileController < ApplicationController
  before_action :authenticate_worker!
  def index
  end

  def show
  end

  def new
  end

  def edit
  end
end

app/helpers/cliente/my_servises_helper.rb
module Cliente::MyServisesHelper
end

app/helpers/cliente/profile_helper.rb
module Cliente::ProfileHelper
end

app/helpers/cliente/tecnicos_interesados_helper.rb
module Cliente::TecnicosInteresadosHelper
    def color_barra_perfil_tecnico( puntos )
        if puntos > 5*0.75
            "progress-bar-success"
        elsif puntos > 5*0.5
            "progress-bar-info"
        elsif puntos > 5*0.25
            "progress-bar-warning"
        else 
            "progress-bar-danger"
        end
    end
end

app/views/cliente/profile/edit.html.erb
<%= render 'cliente/menu' %>
<h1>Cliente::Profile#edit</h1>
<p>Find me in app/views/cliente/profile/edit.html.erb</p>

app/views/cliente/profile/index.html.erb
<div id="content" class="container-fluid"> 
    <div class="row">
  
      <%= render 'cliente/menu' %><!-- Content -->
        <div class="col-lg-9 text-center" style="margin-top:32px;margin-bottom:32px;">

            <!-- Choose Plan -->
            <div class="choose-plan">
              <ul class="row">
                
                <!-- columna1 -->
                <li class="col-md-6">
                  <article>
                    <h4>Datos Personales</h4>
    
                    <ul>
                      <li><p>Nombre: <span class=""><%= current_customer.name%></span></p> </li>
                      <li><p>Usuario: <%= current_customer.user_name%></p></li>
                      <li><p>Direccion: <%= current_customer.address%></p></li>
                      <li></li>
                    </ul>
                    <!-- Choose --> 
                    <p><%= link_to "Editar tus datos", edit_customer_registration_path, class:"btn btn-warning" %></p> </article>
                </li>
                
                <!-- column2 -->
                <li class="col-md-6">
                  <article>
                    <h4>Datos de Contacto</h4>
    
                    <ul>
                      <li><p>Correo: <%= current_customer.email%></p></li>
                      <li><p>Tarjeta de Credito: <%= current_customer.number_card%></p></li>
                      <li><p>Telefono: <%= current_customer.phone_number%></p></li>
                      <li></li>

                    </ul>
                    <!-- Choose --> 
                    <p><%= link_to "Editar tus datos", edit_customer_registration_path, class:"btn btn-warning" %></p> </article>
                </li>
                
              </ul>
            </div>

        </div>
    </div>
</div>

app/views/cliente/profile/new.html.erb
<%= render 'cliente/menu' %>
<h1>Cliente::Profile#new</h1>
<p>Find me in app/views/cliente/profile/new.html.erb</p>

app/views/cliente/profile/show.html.erb
<%= render 'cliente/menu' %>
<h1>Cliente::Profile#show</h1>
<p>Find me in app/views/cliente/profile/show.html.erb</p>